defaults:
  - experiment: example_file
  - dset: debug
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

# Logging and printing, and does not impact training
num_prints: 5
device: cuda
num_workers: 2
verbose: 0
show: 0   # just show the model and its size and exit

# log results
log_results: true
n_bins: 10

# Checkpointing, by default automatically load last checkpoint
checkpoint: true
continue_from: '' # Path the a checkpoint.th file to start from.
# this is not used in the name of the experiment!
# so use a dummy=something not to mixup experiment.
continue_best: false  # continue from best, not last state if continue_from is set.
restart: false # Ignore existing checkpoints
checkpoint_file: checkpoint.th
best_file: best.th  # will contain only best model at any point
history_file: history.json
test_results_file: test_results.json
samples_dir: samples
keep_history: true

# Other stuff
seed: 2036
dummy: '' # use this if you want twice the same exp, with a different name

# Evaluation stuff
pesq: True # compute pesq?
eval_every: 10  # compute test metrics every so epochs
streaming: False  # use streaming evaluation for Demucs
enhance_samples_limit: -1

#wand_b
wandb:
  mode: online  # online/offline/disabled
  log: all # gradients/parameters/all/None
  log_freq: 5
  n_files_to_log: 10 # number or -1 for all files
  tags: []

# Optimization related
optim: adam
lr: 3e-4
scheduler_factor: 1
scheduler_step_size: 20
beta1: 0.8
beta2: 0.999
loss: l1
stft_loss: True
pyramid_loss: False
stft_sc_factor: .5
stft_mag_factor: .5
epochs: 100

# Experiment launching, distributed
ddp: false
ddp_backend: nccl
rendezvous_file: ./rendezvous

# Internal config, don't set manually
rank:
world_size:

# Hydra config
hydra:
  sweep:
    dir: ./outputs/${dset.name}/${experiment.name}
    subdir: ${hydra.job.num}
  run:
    dir: ./outputs/${dset.name}/${experiment.name}
  job:
    config:
      # configuration for the ${hydra.job.override_dirname} runtime variable
      override_dirname:
        kv_sep: '='
        item_sep: ','
        # Remove all paths, as the / in them would mess up things
        # Remove params that would not impact the training itself
        # Remove all slurm and submit params.
        # This is ugly I know...
        exclude_keys: [
          'hydra.job_logging.handles.file.filename',
          'dset.train', 'dset.valid', 'dset.test',
          'num_prints', 'continue_from',
          'device', 'num_workers', 'print_freq', 'restart', 'verbose',
          'log']
  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr